title: Nectar Fusion
description: 'Queer-led fusion partner dance events in Portland, OR. Classes, DJ sets, and social dancing. BIPOC and LGBTQIA2S+ friendly.'
baseurl: ''
url: 'https://nectarfusion.dance'

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
